Data layer xml local source
Joelgh1/Movies_2022 pull request #2
Opened 2022-11-08 19:17 UTC by Joelgh1

## Description de la tarea

Crear fuente de datos local en xml

## ¿Cómo se ha implementado?

He creado una clase repositorio para gestionar las fuentes de datos, como aún no he implementado una fuente remota solo devuelve la información de local.
Para las fuentes de datos locales he creado una interfaz que tiene los métodos indispensables, de esta forma será fácil cambiar entre xml, memoria y base de datos.
He abstraído la librería de serialización (gson en este caso) usando una interfaz con los métodos para serializar y deserializar 
y creando una clase que implementa la interfaz. En esa clase es donde utilizo gson.
La fuente de datos recibe como parámetros un contexto para crear shared preferences y un serializer. Aparte de los métodos propios de la interfaz de local source implemente un método para guardar una única película para facilitar el guardado de una lista de películas.

## Keywords

data layer, xml, shared preferences, serialización, gson, local source

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2022-11-09 16:01 UTC, jmperezra requested changes
Please, revisa los comentarios realizados.

2022-11-09 16:01 UTC, ghost commented on app/src/main/java/com/joelgh/movies_2022/data/MoviesDataRepository.kt
> +class MoviesDataRepository(val localSource: MoviesLocalSource) : MoviesRepository{
Vamos a seguir el patrón de nombres establecidos [aquí](https://iesam-dam.github.io/acceso-a-datos/works-units/architecture/data-sources/local-data-source.html#naming)

2022-11-09 16:01 UTC, ghost commented on app/src/main/java/com/joelgh/movies_2022/data/local/MoviesLocalSource.kt
> +interface MoviesLocalSource {
Please, revisa el naming: [Link](https://iesam-dam.github.io/acceso-a-datos/works-units/architecture/data-sources/)

2022-11-09 16:01 UTC, jmperezra commented on app/src/main/java/com/joelgh/movies_2022/data/local/xml/MoviesXmlLocalDataSource.kt
> +    val sharedPrefs = context.getSharedPreferences("Movies", Context.MODE_PRIVATE)
Por qué has elegido un sharedpreferences a nivel de app? Por otro lado, por qué no metes este string en R.string.XXX ??

2022-11-09 16:01 UTC, jmperezra commented on app/src/main/java/com/joelgh/movies_2022/data/local/xml/MoviesXmlLocalDataSource.kt
> +    private fun saveOne(movie: MovieModel){
saveOne?? mmm quizás podrías usar save(listado) save(unidad)

2022-11-09 17:57 UTC, Joelgh1 reviewed
Cambios hechos

2022-11-09 18:02 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/movies_2022/data/local/xml/MoviesXmlLocalDataSource.kt
> +    private fun saveOne(movie: MovieModel){
Use ese nombre para no confundirme con los métodos

2022-11-09 18:03 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/movies_2022/data/local/xml/MoviesXmlLocalDataSource.kt
> +    val sharedPrefs = context.getSharedPreferences("Movies", Context.MODE_PRIVATE)
Lo hice a nivel de app porque el modelo que hice lo utilizarán tanto el feed como el detalle entonces necesitan acceder los dos al fichero.
Lo de meter el string en el fichero no había caído pero ya lo he añadido

2022-11-09 18:03 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/movies_2022/data/MoviesDataRepository.kt
> +class MoviesDataRepository(val localSource: MoviesLocalSource) : MoviesRepository{
Hecho

2022-11-09 18:03 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/movies_2022/data/local/MoviesLocalSource.kt
> +interface MoviesLocalSource {
Hecho

2022-11-09 18:04 UTC, Joelgh1 reviewed
Ahora sí, todo hecho

2022-11-17 07:42 UTC, josem-perram approved these changes
La PR está bien, sólo una sugerencia de namings.

2022-11-17 07:42 UTC, josem-perram commented on app/src/main/java/com/joelgh/movies_2022/data/local/xml/XmlLocalDataSource.kt
> +    private fun saveOne(movie: MovieModel){
saveOne no me convence mucho je je, puedes usar la sobrecarga de métodos y dejar de nuevo save(xxx)

2022-11-17 12:33 UTC, Joelgh1 commented on app/src/main/java/com/joelgh/movies_2022/data/local/xml/XmlLocalDataSource.kt
> +    private fun saveOne(movie: MovieModel){
Ya que no es urgente haré el cambio en la siguiente pr para no alargar más esta

2022-11-17 12:33 UTC, merged